import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://klaviyo.okta.com/oauth2/v1/authorize?client_id=okta.2b1959c8-bcc0-56eb-a589-cfcfb7422f26&code_challenge=hzcKNdhGnRh50o3pt4-xX7i4hygxK5c_Sy5FaxTo9Bg&code_challenge_method=S256&nonce=70ncw0ISVC15M2UxkP0rPYvui2d4Rz6MnQkGIRszNuN8BKlU9fvc6nvIR0eUSGza&redirect_uri=https%3A%2F%2Fklaviyo.okta.com%2Fenduser%2Fcallback&response_type=code&state=d9cUzfoK3UOW7EYYEfyx0RvlXo4W8F7eRptsDJIrgL3xitvIsFUcLwrYOyHj9n3f&scope=openid%20profile%20email%20okta.users.read.self%20okta.users.manage.self%20okta.internal.enduser.read%20okta.internal.enduser.manage%20okta.enduser.dashboard.read%20okta.enduser.dashboard.manage%20okta.myAccount.sessions.manage%20okta.internal.navigation.enduser.read');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('COTTONdickENERGY1234$');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('link', { name: 'Select Okta Verify.' }).click();
  await page.getByRole('searchbox', { name: 'Search your apps, tab to' }).click();
  await page.getByRole('searchbox', { name: 'Search your apps, tab to' }).fill('fresh');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('row', { name: 'launch app Freshworks' }).getByLabel('launch app Freshworks').click();
  const page1 = await page1Promise;
  await page1.getByRole('link', { name: 'FreshService Klaviyo klaviyo.' }).click();
  await page1.getByRole('menuitem', { name: 'Admin' }).click();
  await page1.getByRole('textbox', { name: 'Search admin' }).click();
  await page1.getByRole('textbox', { name: 'Search admin' }).fill('servi');
  await page1.getByRole('link', { name: 'Service Catalog Manage list' }).click();
  await page1.getByRole('textbox', { name: 'Search service items' }).click();
  await page1.getByRole('textbox', { name: 'Search service items' }).fill('template');
  await page1.getByRole('textbox', { name: 'Search service items' }).press('Enter');
  await page1.getByRole('link', { name: 'IT Workflow V2 Template - App', exact: true }).click();
  await page1.locator('.btn-group > button:nth-child(2)').click();
  await page1.getByRole('link', { name: 'Save As', exact: true }).click();
  await page1.locator('#save_as_item_name').click();
  await page1.locator('#save_as_item_name').click();
  await page1.locator('#save_as_item_name').dblclick();
  await page1.locator('#save_as_item_name').fill('Clover Security');
  await page1.getByRole('link', { name: 'Save', exact: true }).click();
  await page1.getByRole('link', { name: 'Select Role ' }).click();
  await page1.getByText('Role*').first().click();
  await page1.getByRole('textbox', { name: 'Enter or Select' }).fill('');
  await page1.getByText('Enter Text').click();
  await page1.locator('input[name="custom-input"]').dblclick();
  await page1.locator('input[name="custom-input"]').dblclick();
  await page1.locator('input[name="custom-input"]').press('ControlOrMeta+a');
  await page1.locator('input[name="custom-input"]').fill('Clover');
  await page1.getByRole('button', { name: 'Submit' }).click();
  await page1.getByRole('button', { name: 'Done' }).click();
  await page1.locator('#custom_item_field_form').click();
  await page1.locator('#dropdown_title > .pull-right').click();
  await page1.locator('.ficon-sr_paragraph').first().click();
  await page1.locator('.modal-backdrop').click();
  await page1.locator('#para_title > .pull-right').click();
  await page1.locator('.ficon-sr_paragraph').first().click();
  await page1.locator('.ficon-sr_paragraph.solid_icon').click();
  await page1.locator('#FieldLabels > div').first().click();
  await page1.locator('input[name="customlabel"]').dblclick();
  await page1.locator('input[name="customlabel"]').fill('Why do you need access to this role?');
  await page1.locator('input[name="customplaceholder"]').click();
  await page1.locator('input[name="customplaceholder"]').fill('Please be as descriptive as possible.');
  await page1.getByRole('checkbox', { name: 'Display to approver' }).check();
  await page1.getByRole('checkbox', { name: 'Mandatory Field' }).check();
  await page1.getByRole('button', { name: 'Done' }).click();
  await page1.locator('#item_short_description').dblclick();
  await page1.locator('#item_short_description').click();
  await page1.locator('#item_short_description').click();
  await page1.locator('#item_short_description').click();
  await page1.locator('#item_short_description').press('ControlOrMeta+a');
  await page1.locator('#catalog_sidebar').click();
  await page1.locator('#item_short_description').click();
  await page1.locator('#item_short_description').click();
  await page1.locator('#item_short_description').dblclick();
  await page1.locator('#item_short_description').fill('Clover Security');
  await page1.locator('.redactor_editor').first().click();
  await page1.locator('.redactor_editor').first().fill('Clover AI security tool will be used to do Security RFC reviews');
  await page1.locator('.delete_wrapper > .icon-trash').first().click();
  await page1.locator('#confirmModal-submit').click();
  await page1.locator('.btn-group > button:nth-child(2)').click();
  await page1.getByText('Clover Security Published Preview Delete Cancel Save Save & Publish Save as').click();
  await page1.locator('.btn-group > button:nth-child(2)').click();
  await page1.getByRole('link', { name: 'Save & Publish' }).click();
  await page1.locator('#catalog_items_container').click();
  await page2.getByRole('heading', { name: 'General Details  Help' }).click();
});